name: Zulip production suite

on:
  push: {}

defaults:
  run:
    shell: bash

jobs:
  production_upgrade:
    # The production upgrade job starts with a container with a
    # previous Zulip release installed, and attempts to upgrade it to
    # the release tarball built for the current commit being tested.
    #
    # This is intended to catch bugs that result in the upgrade
    # process failing.
    strategy:
      fail-fast: false
      matrix:
        include:
          # Docker images are built from 'tools/ci/Dockerfile'; the comments at
          # the top explain how to build and upload these images.
          - docker_image: zulip/ci:focal-3.4
            name: 3.4 Version Upgrade
            os: focal

    name: ${{ matrix.name  }}
    container:
      image: ${{ matrix.docker_image }}
      options: --init
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Try parts of the upgrade
        run: |
          chmod +x "$GITHUB_WORKSPACE/tools/ci/production-upgrade"
          sudo "$GITHUB_WORKSPACE/tools/ci/production-upgrade"
      - name: Upload strace output
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: strace-logs
          path: /strace-logs.tar.gz
          retention-days: 1
